service: cautious-invention

provider:
  name: aws
  runtime: python3.7
  region: eu-north-1
  deploymentBucket:
    name: serverless-deployments-est2019

package:
  include:
    - handler.py
  exclude:
     - ./**    

functions:
  hello:
    handler: handler.hello