service: cautious-invention

provider:
  name: aws
  runtime: python3.7

# Overwrite defaults here
#  stage: dev
#  region: us-east-1

# Add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# Define service wide environment variables here
#  environment:
#    variable1: value1

# Packaging information
package:
  include:
    - handler.py
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
#    events:
#      - http:
#          path: abc/def
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(3 minutes)
#      - cloudwatchLog: '/aws/lambda/hello'
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    environment:
#      somevariable: somevalue

#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: test-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description here"
#       Value: "Value here"
